name: Test lib

on:
    push:
        branches:
            - master
        paths-ignore:
            - "*.md"
    workflow_dispatch:
    pull_request_review:
        types: [submitted]

jobs:
    tests:
        if: github.event.review.state == 'approved' ||  github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        strategy:
            matrix:
                docker_tags: [latest]
                node_version: [16, 18]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node_version }}
            - name: Docker run containers and tests
              env:
                  GRAPHHOPPER_API_KEY: ${{ secrets.GRAPHHOPPER_API_KEY }}
              run: |
                  docker compose up -d
                  sleep 10
                  npm ci
                  npm test
                  docker compose down
